<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('plants')->insert([
            [
                'scientific_name' => 'Opuntia ficus-indica',
                'common_name' => 'Figuier de Barbarie',
                'family' => 'Cactaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Très faible',
                'soil_requirement' => 'Sablonneux, Caillouteux',
                'soil_ph' => 6.0,
                'temperature_min' => -10.0,
                'temperature_max' => 50.0,
                'humidity_min' => 10.0,
                'humidity_max' => 40.0,
                'description' => 'Le figuier de Barbarie est une plante succulente de la famille des cactacées, connue pour ses fruits comestibles appelés figues de Barbarie.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Phoenix dactylifera',
                'common_name' => 'Palmier Dattier',
                'family' => 'Arecaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Sablonneux',
                'soil_ph' => 6.5,
                'temperature_min' => 5.0,
                'temperature_max' => 50.0,
                'humidity_min' => 20.0,
                'humidity_max' => 60.0,
                'description' => 'Le palmier dattier est un arbre de la famille des arécacées, connu pour ses fruits sucrés, les dattes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Mangifera indica',
                'common_name' => 'Manguier',
                'family' => 'Anacardiaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré à élevé',
                'soil_requirement' => 'Léger, bien drainé, légèrement acide à neutre',
                'soil_ph' => 5.5,
                'temperature_min' => 5.0,
                'temperature_max' => 45.0,
                'humidity_min' => 40.0,
                'humidity_max' => 80.0,
                'description' => 'Le manguier est un arbre tropical de la famille des Anacardiacées, connu pour ses fruits délicieux et sucrés, les mangues.',
                'created_at' => now(),
                'updated_at' => now(),
            ],            
            [
                'scientific_name' => 'Citrullus lanatus',
                'common_name' => 'Pastèque',
                'family' => 'Cucurbitaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Sablonneux, Limoneux',
                'soil_ph' => 6.0,
                'temperature_min' => 20.0,
                'temperature_max' => 40.0,
                'humidity_min' => 30.0,
                'humidity_max' => 60.0,
                'description' => 'La pastèque est une plante de la famille des cucurbitacées, connue pour son gros fruit sucré et juteux.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Malus domestica',
                'common_name' => 'Pomme',
                'family' => 'Rosaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 6.0,
                'temperature_min' => -2.0,
                'temperature_max' => 24.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'description' => 'Le pommier est un arbre caduc de la famille des rosacées, connu pour son fruit sucré, la pomme.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Pyrus communis',
                'common_name' => 'Poire',
                'family' => 'Rosaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil à mi-ombre',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 6.0,
                'temperature_min' => -4.0,
                'temperature_max' => 24.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'description' => 'La poire est un fruit sucré, étroit en haut et large en bas. Elle est riche en fibres et en antioxydants.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Ananas comosus',
                'common_name' => 'Ananas',
                'family' => 'Bromeliaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 5.0,
                'temperature_min' => 16.0,
                'temperature_max' => 32.0,
                'humidity_min' => 50.0,
                'humidity_max' => 70.0,
                'description' => 'L\'ananas est une plante tropicale avec un fruit comestible multiple constitué de baies coalescentes, également appelées ananas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Litchi chinensis',
                'common_name' => 'Litchi',
                'family' => 'Sapindaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 5.0,
                'temperature_min' => 20.0,
                'temperature_max' => 32.0,
                'humidity_min' => 50.0,
                'humidity_max' => 70.0,
                'description' => 'Le litchi est un arbre tropical originaire des provinces du Guangdong et du Fujian, dans le sud-est de la Chine.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Fragaria × ananassa',
                'common_name' => 'Fraise',
                'family' => 'Rosaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Arrosage régulier',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 5.5,
                'temperature_min' => -2.0,
                'temperature_max' => 30.0,
                'humidity_min' => 50.0,
                'humidity_max' => 70.0,
                'description' => 'La fraise des jardins est une espèce hybride largement cultivée du genre Fragaria.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Cocos nucifera',
                'common_name' => 'Noix de coco',
                'family' => 'Arecaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol sablonneux',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Élevé',
                'soil_requirement' => 'Sablonneux',
                'soil_ph' => 5.0,
                'temperature_min' => 20.0,
                'temperature_max' => 32.0,
                'humidity_min' => 60.0,
                'humidity_max' => 95.0,
                'description' => 'Le cocotier est un membre de la famille des palmiers et la seule espèce vivante connue du genre Cocos.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'scientific_name' => 'Prunus avium',
                'common_name' => 'Cerise',
                'family' => 'Rosaceae',
                'image' => 'default_image_url.jpg',
                'growth_conditions' => 'Sol bien drainé',
                'light_requirement' => 'Plein soleil',
                'water_requirement' => 'Modéré',
                'soil_requirement' => 'Limoneux, Sablonneux',
                'soil_ph' => 6.0,
                'temperature_min' => -4.0,
                'temperature_max' => 24.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'description' => 'Le cerisier est un arbre caduc qui produit des fruits comestibles appelés cerises.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
